/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package optimizate;

/**
 *
 * @author sergio andres
 */
public class LavadoraPantalla extends javax.swing.JPanel {

    /**
     * Creates new form LavadoraPantalla
     */
    public LavadoraPantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LavadoraKV = new javax.swing.JLabel();
        EnergiaAhorrada = new javax.swing.JLabel();
        EnergiaDesperdiciada = new javax.swing.JLabel();
        Consejo1LavadoraE = new javax.swing.JLabel();
        Consejo2LavadoraE = new javax.swing.JLabel();
        Consejo3LavadoraE = new javax.swing.JLabel();
        Consejo4LavadoraE = new javax.swing.JLabel();
        Consejo5LavadoraE = new javax.swing.JLabel();
        Consejo5Lavadora = new javax.swing.JCheckBox();
        Consejo4Lavadora = new javax.swing.JCheckBox();
        Consejo3Lavadora = new javax.swing.JCheckBox();
        Consejo2Lavadora = new javax.swing.JCheckBox();
        Consejo1Lavadora = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Separador4 = new javax.swing.JSeparator();
        Separador5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setPreferredSize(new java.awt.Dimension(581, 380));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><b>Tareas  lavadora</b></html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/Lavadora.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><b>Tareas Pendientes lavadora</b></html>");

        LavadoraKV.setText("Energia Gastada: 500 kv");

        EnergiaAhorrada.setText("Energia a ahorrar: 500 kv");

        EnergiaDesperdiciada.setText("Energia a despediciarr: 500 kv");

        Consejo1LavadoraE.setText("Energia ahorrada: 50kv");

        Consejo2LavadoraE.setText("Energia ahorrada: 50kv");

        Consejo3LavadoraE.setText("Energia ahorrada: 50kv");

        Consejo4LavadoraE.setText("Energia ahorrada: 50kv");

        Consejo5LavadoraE.setText("Energia ahorrada: 50kv");

        Consejo5Lavadora.setText("Poner consejos de bombilla aqui");
        Consejo5Lavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo5LavadoraActionPerformed(evt);
            }
        });

        Consejo4Lavadora.setText("Poner consejos de bombilla aqui");
        Consejo4Lavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo4LavadoraActionPerformed(evt);
            }
        });

        Consejo3Lavadora.setText("Poner consejos de bombilla aqui");
        Consejo3Lavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo3LavadoraActionPerformed(evt);
            }
        });

        Consejo2Lavadora.setText("Poner consejos de bombilla aqui");
        Consejo2Lavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo2LavadoraActionPerformed(evt);
            }
        });

        Consejo1Lavadora.setText("Poner consejos de bombilla aqui");
        Consejo1Lavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo1LavadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LavadoraKV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnergiaAhorrada)
                        .addGap(29, 29, 29)
                        .addComponent(EnergiaDesperdiciada))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Consejo1Lavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Consejo1LavadoraE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consejo5Lavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo5LavadoraE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consejo4Lavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo4LavadoraE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consejo3Lavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo3LavadoraE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consejo2Lavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo2LavadoraE))
                    .addComponent(Separador5)
                    .addComponent(Separador4)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LavadoraKV)
                    .addComponent(EnergiaAhorrada)
                    .addComponent(EnergiaDesperdiciada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo1Lavadora)
                    .addComponent(Consejo1LavadoraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo2Lavadora)
                    .addComponent(Consejo2LavadoraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo3Lavadora)
                    .addComponent(Consejo3LavadoraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo4Lavadora)
                    .addComponent(Consejo4LavadoraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo5Lavadora)
                    .addComponent(Consejo5LavadoraE))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Consejo5LavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo5LavadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo5LavadoraActionPerformed

    private void Consejo4LavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo4LavadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo4LavadoraActionPerformed

    private void Consejo3LavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo3LavadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo3LavadoraActionPerformed

    private void Consejo2LavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo2LavadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo2LavadoraActionPerformed

    private void Consejo1LavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo1LavadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo1LavadoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox Consejo1Lavadora;
    protected javax.swing.JLabel Consejo1LavadoraE;
    protected javax.swing.JCheckBox Consejo2Lavadora;
    protected javax.swing.JLabel Consejo2LavadoraE;
    protected javax.swing.JCheckBox Consejo3Lavadora;
    protected javax.swing.JLabel Consejo3LavadoraE;
    protected javax.swing.JCheckBox Consejo4Lavadora;
    protected javax.swing.JLabel Consejo4LavadoraE;
    protected javax.swing.JCheckBox Consejo5Lavadora;
    protected javax.swing.JLabel Consejo5LavadoraE;
    protected javax.swing.JLabel EnergiaAhorrada;
    protected javax.swing.JLabel EnergiaDesperdiciada;
    protected javax.swing.JLabel LavadoraKV;
    protected javax.swing.JSeparator Separador4;
    protected javax.swing.JSeparator Separador5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
