/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package optimizate;

/**
 *
 * @author sergio andres
 */
public class NeveraPantalla extends javax.swing.JPanel {

    /**
     * Creates new form NeveraPantalla
     */
    public NeveraPantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NeveraKV = new javax.swing.JLabel();
        EnergiaAhorrada = new javax.swing.JLabel();
        EnergiaDesperdiciada = new javax.swing.JLabel();
        Consejo1NeveraE = new javax.swing.JLabel();
        Consejo2NeveraE = new javax.swing.JLabel();
        Consejo3NeveraE = new javax.swing.JLabel();
        Consejo4NeveraE = new javax.swing.JLabel();
        Consejo5NeveraE = new javax.swing.JLabel();
        Consejo5Nevera = new javax.swing.JCheckBox();
        Consejo4Nevera = new javax.swing.JCheckBox();
        Consejo3Nevera = new javax.swing.JCheckBox();
        Consejo2Nevera = new javax.swing.JCheckBox();
        Consejo1Nevera = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Separador4 = new javax.swing.JSeparator();
        Separador5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><b>Tareas  Nevera</b></html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/Nevera.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><b>Tareas Pendientes nevera</b></html>");

        NeveraKV.setText("Energia Gastada: 500 kv");

        EnergiaAhorrada.setText("Energia a ahorrar: 500 kv");

        EnergiaDesperdiciada.setText("Energia a despediciarr: 500 kv");

        Consejo1NeveraE.setText("Energia ahorrada: 50kv");

        Consejo2NeveraE.setText("Energia ahorrada: 50kv");

        Consejo3NeveraE.setText("Energia ahorrada: 50kv");

        Consejo4NeveraE.setText("Energia ahorrada: 50kv");

        Consejo5NeveraE.setText("Energia ahorrada: 50kv");

        Consejo5Nevera.setText("Poner consejos de bombilla aqui");
        Consejo5Nevera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo5NeveraActionPerformed(evt);
            }
        });

        Consejo4Nevera.setText("Poner consejos de bombilla aqui");
        Consejo4Nevera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo4NeveraActionPerformed(evt);
            }
        });

        Consejo3Nevera.setText("Poner consejos de bombilla aqui");
        Consejo3Nevera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo3NeveraActionPerformed(evt);
            }
        });

        Consejo2Nevera.setText("Poner consejos de bombilla aqui");
        Consejo2Nevera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo2NeveraActionPerformed(evt);
            }
        });

        Consejo1Nevera.setText("Poner consejos de bombilla aqui");
        Consejo1Nevera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consejo1NeveraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(NeveraKV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnergiaAhorrada)
                        .addGap(29, 29, 29)
                        .addComponent(EnergiaDesperdiciada))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Consejo1Nevera, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Consejo1NeveraE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consejo5Nevera, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo5NeveraE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consejo4Nevera, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo4NeveraE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consejo3Nevera, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo3NeveraE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consejo2Nevera, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Consejo2NeveraE))
                    .addComponent(Separador5)
                    .addComponent(Separador4)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NeveraKV)
                    .addComponent(EnergiaAhorrada)
                    .addComponent(EnergiaDesperdiciada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo1Nevera)
                    .addComponent(Consejo1NeveraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo2Nevera)
                    .addComponent(Consejo2NeveraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo3Nevera)
                    .addComponent(Consejo3NeveraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo4Nevera)
                    .addComponent(Consejo4NeveraE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consejo5Nevera)
                    .addComponent(Consejo5NeveraE))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Consejo5NeveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo5NeveraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo5NeveraActionPerformed

    private void Consejo4NeveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo4NeveraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo4NeveraActionPerformed

    private void Consejo3NeveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo3NeveraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo3NeveraActionPerformed

    private void Consejo2NeveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo2NeveraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo2NeveraActionPerformed

    private void Consejo1NeveraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consejo1NeveraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consejo1NeveraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox Consejo1Nevera;
    protected javax.swing.JLabel Consejo1NeveraE;
    protected javax.swing.JCheckBox Consejo2Nevera;
    protected javax.swing.JLabel Consejo2NeveraE;
    protected javax.swing.JCheckBox Consejo3Nevera;
    protected javax.swing.JLabel Consejo3NeveraE;
    protected javax.swing.JCheckBox Consejo4Nevera;
    protected javax.swing.JLabel Consejo4NeveraE;
    protected javax.swing.JCheckBox Consejo5Nevera;
    protected javax.swing.JLabel Consejo5NeveraE;
    protected javax.swing.JLabel EnergiaAhorrada;
    protected javax.swing.JLabel EnergiaDesperdiciada;
    protected javax.swing.JLabel NeveraKV;
    protected javax.swing.JSeparator Separador4;
    protected javax.swing.JSeparator Separador5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
